[package]
name = "city_strides_utils"
version = "0.1.0"
edition = "2021"

[lib]
name = "city_strides_utils"
path = "utils.rs"

[dependencies]
serde = "1.0"
serde_json = "1.0"
itertools = "0.11"
csv = "1.1"
haversine = "0.2.1"
serde_derive = "1.0"
